name: Flutter Nightly Build exe apk

# on:
#   schedule:
#     # schedule build every night
#     - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/exe-Android.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "nightly" 
